language: python
python:
  - "3.6"
install: make ci-install
script: make test
env:
  global:
    - CC_TEST_REPORTER_ID=5e14c800f18e5370fb31802d65a6eef510f11280084074ff71293947273fc50c
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
